// Code generated by rscli. DO NOT EDIT.

package config

type configKey string

const (
	AppInfoName            = "app_info_name"
	AppInfoStartupDuration = "app_info_startup_duration"
	AppInfoVersion         = "app_info_version"
	ServerRestAPIPort      = "server_rest_api_port"
)
